### ISSUE TITLE
Unable to use Artist Artwork

### ISSUE THREAD

**Issue by Palumbo93** [rryam/MusadoraKit#13]
I installed your package (amazing btw, I would love to talk to you about it) and I am no longer able to access the Artwork property on Artists. Any idea why?

**Comment by rudrankriyam** [comment]
Heya! I am unsure if I ever added the `artwork` on `Artist` in MusadoraKit. I wrote an [article](https://rudrank.blog/musickit-for-swift-artist-artwork) about it but avoided adding it in MusadoraKit because of legal issues and my solution depends on a third-party dependency. 

Also, in Xcode 14, this property is available natively
